### ISSUE TITLE
Setting up Cron jobs in cli

### ISSUE THREAD

**Issue by achekulaev** [docksal/blog#10]
See https://github.com/docksal/docksal/pull/671 for reference

**Comment by sean-e-dietrich** [comment]
Submitted a post here for review https://medium.com/p/43fc69d7b29b/edit

**Comment by shelane** [comment]
Looks good.

**Comment by achekulaev** [comment]
Looks great! Published https://blog.docksal.io/running-scheduled-events-with-docksal-43fc69d7b29b
